sudo: true
language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-22  ANDROID_ABI=armeabi-v7a
  global:
    - ANDROID_HOME=/usr/local/android-sdk-25.0.2
    - TOOLS=${ANDROID_HOME}/tools
    - TEMP=${ANDROID_HOME}/:${TOOLS}/:${TOOLS}/bin:${TOOLS}/emulator:${ANDROID_HOME}/platform-tools
    - PATH=${TEMP}:${PATH}
before_install:
   - echo y | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
   - echo y | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    - tools
  

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-25
    - android-22

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    #- sys-img-x86-android-22
before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &    
script:
  - ulimit -a
  - ./gradlew build connectedAndroidTest --stacktrace
after_success:
  - bash <(curl -s https://codecov.io/bash)

