package uk.colessoft.android.hilllist.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

import java.util.Date

@Entity(tableName = "hills")
data class Hill(
        @PrimaryKey val _id: Int,
        @ColumnInfo(name = "Name") val hillname: String?,
        @ColumnInfo(name = "Parent (SMC)") val parentSMC: String?,
        @ColumnInfo(name = "Parent name (SMC)") val parentnameSMC: String?,
        @ColumnInfo(name = "Section") val hSection: String?,
        @ColumnInfo(name = "Section name") val sectionname: String?,
        @ColumnInfo(name = "Area") val area: String?,
        @ColumnInfo(name = "Island") val island: String?,
        @ColumnInfo(name = "Topo Section") val topoSection: String?,
        @ColumnInfo(name = "County") val county: String?,
        @ColumnInfo(name = "Classification") val classification: String?,
        @ColumnInfo(name = "Map 1:50k") val map: String?,
        @ColumnInfo(name = "Map 1:25k") val map25: String?,
        @ColumnInfo(name = "Metres") val heightm: Float?,
        @ColumnInfo(name = "Feet") val heightf: Float?,
        @ColumnInfo(name = "Grid ref") val gridref: String?,
        @ColumnInfo(name = "Grid ref 10") val gridref10: String?,
        @ColumnInfo(name = "Drop") val drop: Float?,
        @ColumnInfo(name = "Col grid ref") val colgridref: String?,
        @ColumnInfo(name = "Col height") val colheight: Float?,
        @ColumnInfo(name = "Feature") val feature: String?,
        @ColumnInfo(name = "Observations") val observations: String?,
        @ColumnInfo(name = "Survey") val survey: String?,
        @ColumnInfo(name = "Climbed") val climbed: String?,
        @ColumnInfo(name = "Country") val country: String?,
        @ColumnInfo(name = "County Top") val countyTop: String?,
        @ColumnInfo(name = "Revision") val revision: Date?,
        @ColumnInfo(name = "Comments") val comments: String?,
        @ColumnInfo(name = "Streetmap/OSiViewer") val streetmap: String?,
        @ColumnInfo(name = "Geograph/MountainViews") val geographMountainViews: String?,
        @ColumnInfo(name = "HillDetail-bagging") val hillBagging: String?,
        @ColumnInfo(name = "Xcoord") val xcoord: Int?,
        @ColumnInfo(name = "Ycoord") val ycoord: Int?,
        @ColumnInfo(name = "Latitude") val latitude: Double?,
        @ColumnInfo(name = "Longitude") val longitude: Double?,
        @ColumnInfo(name = "GridrefXY") val gridrefXY: String?,
        @ColumnInfo(name = "_Section") val _section: String?,
        @ColumnInfo(name = "Parent (Ma)") val parentMa: String?,
        @ColumnInfo(name = "Parent name (Ma)") val parentnameMa: String?,
        @ColumnInfo(name = "MVNumber") val mVNumber: String?,
        @ColumnInfo(name = "Ma") val ma: String?,
        @ColumnInfo(name = "Ma=") val maTop: String?,
        @ColumnInfo(name = "Hu") val hu: String?,
        @ColumnInfo(name = "Hu=") val huTop: String?,
        @ColumnInfo(name = "Tu") val tu: String?,
        @ColumnInfo(name = "Tu=") val tuTop: String?,
        @ColumnInfo(name = "Sim") val sim: String?,
        @ColumnInfo(name = "M") val m: String?,
        @ColumnInfo(name = "MT") val mT: String?,
        @ColumnInfo(name = "F") val f: String?,
        @ColumnInfo(name = "C") val c: String?,
        @ColumnInfo(name = "G") val g: String?,
        @ColumnInfo(name = "D") val d: String?,
        @ColumnInfo(name = "DT") val dT: String?,
        @ColumnInfo(name = "Mur") val mur: String?,
        @ColumnInfo(name = "CT") val cT: String?,
        @ColumnInfo(name = "GT") val gT: String?,
        @ColumnInfo(name = "Hew") val hew: String?,
        @ColumnInfo(name = "N") val n: String?,
        @ColumnInfo(name = "5") val five: String?,
        @ColumnInfo(name = "5D") val fiveD: String?,
        @ColumnInfo(name = "5H") val fiveH: String?,
        @ColumnInfo(name = "4") val four: String?,
        @ColumnInfo(name = "3") val three: String?,
        @ColumnInfo(name = "2") val two: String?,
        @ColumnInfo(name = "1") val one: String?,
        @ColumnInfo(name = "1=") val oneTop: String?,
        @ColumnInfo(name = "0") val zero: String?,
        @ColumnInfo(name = "W") val w: String?,
        @ColumnInfo(name = "WO") val wO: String?,
        @ColumnInfo(name = "B") val b: String?,
        @ColumnInfo(name = "CoH") val coH: String?,
        @ColumnInfo(name = "CoH=") val coHTop: String?,
        @ColumnInfo(name = "CoU") val coU: String?,
        @ColumnInfo(name = "CoU=") val coUTop: String?,
        @ColumnInfo(name = "CoA") val coA: String?,
        @ColumnInfo(name = "CoA=") val coATop: String?,
        @ColumnInfo(name = "CoL") val coL: String?,
        @ColumnInfo(name = "CoL=") val coLTop: String?,
        @ColumnInfo(name = "SIB") val sIB: String?,
        @ColumnInfo(name = "sMa") val sMa: String?,
        @ColumnInfo(name = "sHu") val sHu: String?,
        @ColumnInfo(name = "sSim") val sSim: String?,
        @ColumnInfo(name = "s5") val s5: String?,
        @ColumnInfo(name = "s5D") val s5D: String?,
        @ColumnInfo(name = "s5H") val s5H: String?,
        @ColumnInfo(name = "s5M") val s5M: String?,
        @ColumnInfo(name = "s4") val s4: String?,
        @ColumnInfo(name = "Sy") val sy: String?,
        @ColumnInfo(name = "Fel") val fel: String?,
        @ColumnInfo(name = "BL") val bL: String?,
        @ColumnInfo(name = "Bg") val bg: String?,
        @ColumnInfo(name = "T100") val t100: String?,
        @ColumnInfo(name = "xMT") val xMT: String?,
        @ColumnInfo(name = "xC") val xC: String?,
        @ColumnInfo(name = "xG") val xG: String?,
        @ColumnInfo(name = "xN") val xN: String?,
        @ColumnInfo(name = "xDT") val xDT: String?,
        @ColumnInfo(name = "Dil") val dil: String?,
        @ColumnInfo(name = "VL") val vL: String?,
        @ColumnInfo(name = "A") val a: String?,
        @ColumnInfo(name = "5M") val fiveM: String?,
        @ColumnInfo(name = "Ca") val ca: String?,
        @ColumnInfo(name = "Bin") val bin: String?,
        @ColumnInfo(name = "O") val o: String?,
        @ColumnInfo(name = "Un") val un: String?)


